name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # sistema onde o pipeline vai correr (Linux)

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # versão do Python a usar

      - name: Instalar dependências (se existirem)
        run: 
          python -m pip install --upgrade pip

      - name: Testar se o código corre
        run: 
          python main.py
    
